pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all status checks and has been reviewed
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=Harvey-Reginald-Specter # require manual-merge when auto-approved
    actions:
      merge:
        method: merge
        commit_message_template: >
          Merge: {{ title.strip() }}
      comment:
        message: This Pull request satisfies all status-checks and will be automatically merged soon.

  - name: Add 'Manual-Merge' label to PR when Auto-Reviewed
    conditions:
      - approved-reviews-by=Harvey-Reginald-Specter
      - -label=manual-merge
    actions:
      label:
        add:
          - "manual-merge"
      comment:
        message: This Pull request has been auto-reviewed and is ready for manual merge.

  - name: Auto-Assign Marty-Byrde as Reviewer when Status Checks Pass and Marty-Byrde is not the Author
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - -approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=Harvey-Reginald-Specter
      - -author=Marty-Byrde
      - -review-requested=Marty-Byrde # has not been requested for review
    actions:
      request_reviews:
        users:
          - "Marty-Byrde"
      comment:
        message: "Auto-Assigned Marty-Byrde as Reviewer to this Pull Request."

  - name: Auto-Assign MrsicMarko as Reviewer when Status Checks Pass and MrsicMarko is not the Author
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - -approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=Harvey-Reginald-Specter
      - -author=MrsicMarko
      - -review-requested=MrsicMarko # has not been requested for review
    actions:
      request_reviews:
        users:
          - "MrsicMarko"
      comment:
        message: "Auto-Assigned MrsicMarko as Reviewer to this Pull Request."

  - name: Auto-Assign Pull request author to Pull request
    conditions:
      - "#files > 1"
    actions:
      assign:
        add_users:
          - "{{ author }}"

  - name: Automatic Update-Branch when Main is ahead
    conditions:
      - base = main
      - "#commits-behind > 0"
    actions:
      update:
      comment:
        message: "@{{ author }} This Pull request has been automatically updated, because the main branch was ahead."


