import type { Metadata } from 'next'
import './globals.css'
import SideBar from '@/components/root/SideBar'
import { twMerge } from 'tailwind-merge'
import { MainContentShiftBreakpoints } from '@/config/SideBarConfig'
import React from 'react'
import AuthProvider from '@/components/root/AuthProvider'
import getColorMode from '@/lib/getColorMode'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const colorMode = getColorMode()

  return (
    <html lang='en' className={twMerge('', colorMode)}>
      <body className={`bg-gray-100 dark:bg-neutral-800 text-gray-700 dark:text-gray-200`}>
        <SideBar />
        <AuthProvider>
          <div className={twMerge('p-4', MainContentShiftBreakpoints)}>{children}</div>
        </AuthProvider>
      </body>
    </html>
  )
}
