name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      NEXT_AUTH_GITHUB_ID: ${{ secrets.NEXT_AUTH_GITHUB_ID }}
      NEXT_AUTH_GITHUB_SECRET: ${{ secrets.NEXT_AUTH_GITHUB_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name as environment variable
        run: echo "LOWER_REPO_NAME=$(echo ${{ env.REPO_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          echo "NEXT_AUTH_GITHUB_ID=${{ env.NEXT_AUTH_GITHUB_ID }}" >> .env
          echo "NEXT_AUTH_GITHUB_SECRET=${{ env.NEXT_AUTH_GITHUB_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ env.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }}" >> .env

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ env.LOWER_REPO_NAME }}:latest .

      - name: Push the image
        run: docker push ghcr.io/${{ env.LOWER_REPO_NAME }}:latest

      - name: Set lowercase package name as environment variable
        run: echo "LOWER_PACKAGE_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Delete old docker-image package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.LOWER_PACKAGE_NAME }}
          owner: 'kilowatt-commando'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 2